/** SVN-compatible UI labels — avoid Git terminology */
export const SVN_LABELS = {
  checkout: 'SVN Checkout',
  update: 'SVN Update',
  commit: 'SVN Commit',
  diff: 'SVN Diff',
  log: 'SVN Log',
  revert: 'SVN Revert',
  status: 'Check for Modifications',
  add: 'SVN Add',
  delete: 'SVN Delete',
  rename: 'SVN Rename',
  cleanup: 'SVN Cleanup',
  blame: 'SVN Blame',
  resolve: 'SVN Resolve',
  lock: 'SVN Lock',
  unlock: 'SVN Unlock',
  properties: 'SVN Properties',
  ignore: 'Add to ignore list',
  export: 'SVN Export',
  import: 'SVN Import',
  switch: 'SVN Switch',
  relocate: 'SVN Relocate',
  branchTag: 'Branch/Tag',
  branch: 'Create Branch',
  tag: 'Create Tag',
  merge: 'SVN Merge',
  repoBrowser: 'Repo Browser',
  reviewRequest: 'SVN Review Request',
  mergeApproval: 'Branch Merge Approval',
} as const;
